base_url = "https://dladowitz.github.io/BitcoinBuilderSF/"
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["feed.xml"]

[markdown]
highlight_code = false

[extra]
